version: "3.9"
services:
  historico:
    build:
      context: .
      dockerfile: ./apis/historico/Dockerfile
    ports:
      - "4001:4001"

  resultado:
    build:
      context: .
      dockerfile: ./packages/resultado/Dockerfile
    ports:
      - "4002:4002"

  gateway-api:
    build:
      context: .
      dockerfile: ./packages/gateway/Dockerfile
    ports:
      - "4003:4003"
    environment:
      - DICE_API_URL=http://dice-api:4002
      - SETTINGS_API_URL=http://settings-api:4001
